version: '3'

services:
  storeManagement-psql:
    image: bitnami/postgresql:latest
    ports:
      - 127.0.0.1:5466:5432
    volumes:
      - ./psqldata:/var/lib/postgresql/data
    environment:
      - POSTGRESQL_PASSWORD=123456
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=storeManagement